//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoHanh
    {
        public BaoHanh()
        {
            this.ChiTietDatHangs = new HashSet<ChiTietDatHang>();
        }
    
        public string MaBH { get; set; }
        public string TenBH { get; set; }
        public int ID { get; set; }
    
        public virtual ICollection<ChiTietDatHang> ChiTietDatHangs { get; set; }
    }
}
