//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDatHang
    {
        public string MaHang { get; set; }
        public int SoHoaDon { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string MaBH { get; set; }
        public Nullable<decimal> TongGia { get; set; }
        public int ID { get; set; }
    
        public virtual BaoHanh BaoHanh { get; set; }
        public virtual DonDatHang DonDatHang { get; set; }
        public virtual MatHang MatHang { get; set; }
    }
}
